# Generated by Django 3.2.12 on 2022-06-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_merge_20220602_0926'),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesent',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.team'),
        ),
    ]
