# Generated by Django 4.0.4 on 2022-06-23 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_suppliers_landlord'),
        ('properties', '0023_tenants_deleted'),
        ('register', '0027_alter_customuser_clients_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0003_messagesent_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_sent', models.DateTimeField()),
                ('message', models.TextField(default='')),
                ('subject', models.CharField(max_length=120, null=True)),
                ('via', models.CharField(default='', max_length=50)),
                ('unkonwn_email', models.EmailField(default=None, max_length=254, null=True)),
                ('unkonwn_phone', models.CharField(default=None, max_length=120, null=True)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.organizationclient')),
                ('sent_by_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers')),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.tenants')),
            ],
        ),
        migrations.DeleteModel(
            name='MessageSent',
        ),
    ]
