# Generated by Django 4.0.4 on 2022-05-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_rename_message_subject_messagesent_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesent',
            name='via',
            field=models.CharField(default='', max_length=50),
        ),
    ]
