# Generated by Django 4.0.4 on 2022-06-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_suppliers_landlord'),
        ('properties', '0024_unit_accessibility_features_unit_ad_title_and_more'),
        ('communications', '0005_remove_message_client_alter_message_sent_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tenant',
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_sent_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.tenants'),
        ),
        migrations.AddField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
