# Generated by Django 4.0.4 on 2022-05-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_units_unit'),
        ('communications', '0005_remove_messagesent_destinatary_messagesent_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesent',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.tenants'),
        ),
    ]
