# Generated by Django 4.0.4 on 2022-06-23 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_remove_message_supplier_remove_message_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='communications.conversation'),
        ),
    ]
