# Generated by Django 4.0.4 on 2022-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_message_conversation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='received',
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.conversation'),
        ),
    ]
