# Generated by Django 4.0.2 on 2022-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='conversation',
            new_name='chat',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='chat/files/chat-files'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='chat/files/chat-images'),
        ),
    ]
