# Generated by Django 4.0.4 on 2022-06-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_chat', '0002_rename_conversation_chatmessage_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_sent_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message_sent_by',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
