# Generated by Django 4.0.4 on 2022-06-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0046_alter_customuser_clients_access'),
        ('inter_chat', '0003_chat_last_message_sent_date_alter_chat_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='register.organizationclient'),
        ),
    ]
