# Generated by Django 4.0.4 on 2022-05-12 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0006_remove_units_tenant_id_units_debt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=70)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_paid', models.CharField(max_length=70)),
                ('Tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('payment_date',),
            },
        ),
        migrations.CreateModel(
            name='UnitPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=70)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference_code', models.CharField(max_length=100)),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units')),
            ],
            options={
                'ordering': ('payment_date',),
            },
        ),
    ]
