# Generated by Django 4.0.4 on 2022-05-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=70)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reference_code', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('payment_date',),
            },
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=70)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('plan_paid', models.CharField(max_length=70)),
            ],
            options={
                'ordering': ('payment_date',),
            },
        ),
    ]
