# Generated by Django 3.2.12 on 2022-06-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpayments',
            name='comments',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='unitpayments',
            name='reference_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
