# Generated by Django 4.0.4 on 2022-05-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayments',
            name='month',
            field=models.CharField(default='', max_length=120),
        ),
    ]
