# Generated by Django 4.0.4 on 2022-05-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='Tenant',
            new_name='user',
        ),
    ]
