# Generated by Django 3.2.12 on 2022-06-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220601_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpayments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpayments',
            options={},
        ),
    ]
