# Generated by Django 4.0.4 on 2022-05-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_units_main_tenant_name'),
        ('payments', '0003_rename_tenant_userpayments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayments',
            name='comments',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='unitpayments',
            name='status',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='unitpayments',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.tenants'),
        ),
    ]
