# Generated by Django 4.0.4 on 2022-05-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_unitpayments_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitpayments',
            old_name='Unit',
            new_name='unit',
        ),
    ]
