# Generated by Django 4.0.4 on 2022-06-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220601_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpayments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpayments',
            options={},
        ),
    ]
