# Generated by Django 4.0.4 on 2022-06-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_unitpayments_options_and_more'),
        ('payments', '0004_auto_20220601_1912'),
    ]

    operations = [
    ]
