# Generated by Django 4.0.4 on 2022-05-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_unitpayments_comments_unitpayments_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='unitpayments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.status'),
        ),
    ]
