# Generated by Django 4.0.4 on 2022-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_unitmonthlypayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmonthlypayments',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='unitmonthlypayments',
            name='month',
            field=models.IntegerField(default=1),
        ),
    ]
