# Generated by Django 4.0.4 on 2022-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_unitmonthlypayments_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentPaymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
