# Generated by Django 4.0.4 on 2022-06-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_currentpaymentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitmonthlypayments',
            old_name='pay_on_time',
            new_name='paid_on_time',
        ),
    ]
