# Generated by Django 4.0.4 on 2022-06-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_rename_pay_on_time_unitmonthlypayments_paid_on_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='payment_amount',
            new_name='debt',
        ),
    ]
