# Generated by Django 4.0.4 on 2022-06-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_payment_amount_userpayments_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitmonthlypayments',
            old_name='amount_to_pay',
            new_name='debt',
        ),
        migrations.RenameField(
            model_name='userpayments',
            old_name='debt',
            new_name='payment_amount',
        ),
    ]
