# Generated by Django 4.0.4 on 2022-07-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0062_alter_customuser_clients_access'),
        ('properties', '0027_remove_tenants_date_deposit_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fields', models.JSONField()),
                ('link', models.CharField(default='__no_link__', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_time_edited', models.DateTimeField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='register.organizationclient')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('last_edition_made_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_edition_made_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='properties.unit')),
            ],
        ),
    ]
