# Generated by Django 4.0.4 on 2022-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_number_of_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
