# Generated by Django 4.0.4 on 2022-06-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users_taged',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='commentanswer',
            name='users_taged',
            field=models.JSONField(default=list),
        ),
    ]
