# Generated by Django 4.0.4 on 2022-06-20 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='text',
        ),
        migrations.AddField(
            model_name='todolist',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list.todolist')),
            ],
        ),
    ]
