# Generated by Django 4.0.4 on 2022-06-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_remove_todolist_completed_remove_todolist_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='task',
        ),
    ]
