# Generated by Django 4.0.4 on 2022-06-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_rename_text_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='onwer',
            new_name='owner',
        ),
    ]
