# Generated by Django 4.0.4 on 2022-05-05 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_alter_properties_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_aate', models.JSONField()),
                ('adults_information', models.JSONField()),
                ('appointment', models.DateTimeField()),
                ('current_address', models.CharField(max_length=400)),
                ('current_landlord_name', models.CharField(max_length=100)),
                ('current_landlord_phone', models.CharField(max_length=100)),
                ('duratin_of_lease', models.CharField(max_length=25)),
                ('expected_renting_duration', models.IntegerField()),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=19)),
                ('length_of_time_at_current_address', models.CharField(max_length=400)),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('will_be_pets', models.BooleanField()),
                ('pets', models.JSONField()),
                ('previous_unit_time', models.CharField(max_length=255)),
                ('preferred_move_in_date', models.DateField()),
                ('reason_for_moving', models.TextField()),
                ('relevant_information', models.TextField()),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('property_manager', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='properties.units')),
            ],
        ),
    ]
