# Generated by Django 4.0.4 on 2022-05-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='availability_aate',
            new_name='availability_date',
        ),
    ]
