# Generated by Django 4.0.4 on 2022-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_rename_availability_aate_candidate_availability_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='will_be_pets',
        ),
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='pets',
            field=models.CharField(max_length=100),
        ),
    ]
