# Generated by Django 4.0.4 on 2022-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='property_manager',
        ),
    ]
