# Generated by Django 4.0.4 on 2022-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='facebook_account',
            field=models.CharField(default='', max_length=500),
        ),
    ]
