# Generated by Django 4.0.4 on 2022-05-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='viewing_comments',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='viewing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='viewing_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='viewing_score',
            field=models.IntegerField(null=True),
        ),
    ]
