# Generated by Django 4.0.4 on 2022-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_property_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='current_landlord_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_landlord_phone',
        ),
        migrations.AddField(
            model_name='candidate',
            name='children_ages',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_information',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='length_of_time_at_current_job',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
