# Generated by Django 4.0.4 on 2022-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_will_be_pets_candidate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='family_income',
            field=models.CharField(max_length=50),
        ),
    ]
