# Generated by Django 4.0.4 on 2022-05-10 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0003_alter_candidate_viewing_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='living_references_check',
            new_name='living_references_checked',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='work_references_check',
            new_name='work_references_checked',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='property_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units'),
        ),
    ]
