# Generated by Django 4.0.4 on 2022-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_current_landlord_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='availability_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='previous_unit_time',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='children_ages',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
