# Generated by Django 4.0.4 on 2022-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_family_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='expected_renting_duration',
            field=models.CharField(max_length=100),
        ),
    ]
