# Generated by Django 4.0.4 on 2022-05-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('link_name', models.CharField(max_length=150)),
                ('link_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400)),
                ('coordinates', models.JSONField(null=True)),
                ('img', models.ImageField(null=True, upload_to='properties')),
                ('maps_url', models.URLField(default='')),
                ('name', models.CharField(default='', max_length=100)),
                ('number_of_units', models.IntegerField(default=0)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True)),
                ('photos', models.JSONField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('year_bought', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deposit_received', models.DateField(default=None, null=True)),
                ('email', models.CharField(default='', max_length=50)),
                ('email2', models.CharField(max_length=50, null=True)),
                ('emergency_contact', models.CharField(default='', max_length=50)),
                ('emergency_contact_name', models.CharField(default='', max_length=50, null=True)),
                ('lease_start_date', models.DateField(default=None, null=True)),
                ('lease_expiration_date', models.DateField(default=None, null=True)),
                ('payments_delay', models.IntegerField(default=0)),
                ('payments_on_time', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('phone2', models.CharField(default=None, max_length=50, null=True)),
                ('preferred_communications', models.CharField(default='', max_length=20)),
                ('role', models.CharField(default='', max_length=50)),
                ('secondary_communications', models.CharField(default=None, max_length=20, null=True)),
                ('standing_qualification', models.IntegerField(default=0)),
                ('tenant_type', models.CharField(default='main', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_conditioning', models.BooleanField(default=False)),
                ('appliances', models.JSONField()),
                ('bathrooms', models.IntegerField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('details', models.JSONField(null=True)),
                ('date_deposit_received', models.DateField(null=True)),
                ('extra_resident_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('extra_resident', models.IntegerField(default=0)),
                ('heating_type', models.CharField(default='', max_length=50)),
                ('has_pet', models.BooleanField(default=True)),
                ('lease_type', models.CharField(max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('notes', models.TextField(default='')),
                ('number_of_pets', models.IntegerField(default=0)),
                ('number_of_residents', models.IntegerField(default=0)),
                ('payments_email', models.CharField(default='', max_length=100)),
                ('parking_available', models.BooleanField(default=False)),
                ('parking_type', models.CharField(default='', max_length=50)),
                ('pet_fee', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('pet_policy', models.CharField(default='', max_length=100)),
                ('pets_living', models.CharField(default='', max_length=50)),
                ('rented', models.BooleanField(default=False)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('rooms', models.IntegerField(default=0)),
                ('services', models.JSONField()),
                ('square_feet_area', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('shed', models.BooleanField(default=False)),
                ('unit', models.IntegerField(default=1)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties')),
            ],
        ),
    ]
