# Generated by Django 4.0.4 on 2022-05-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='tenant',
            new_name='tenant_id',
        ),
    ]
