# Generated by Django 4.0.4 on 2022-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit',
            field=models.IntegerField(default=1),
        ),
    ]
