# Generated by Django 4.0.4 on 2022-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='properie_type',
            new_name='property_type',
        ),
        migrations.AlterField(
            model_name='properties',
            name='img',
            field=models.ImageField(upload_to='properties'),
        ),
        migrations.AlterField(
            model_name='units',
            name='date_deposit_received',
            field=models.DateField(),
        ),
    ]
