# Generated by Django 3.2.12 on 2022-05-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='servicess',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
