# Generated by Django 3.2.12 on 2022-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_units_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='servicesss',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
