# Generated by Django 4.0.4 on 2022-05-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_units_main_tenant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=120)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='main_tenant',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='units',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
