# Generated by Django 4.0.4 on 2022-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_properie_type_properties_property_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_bought',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='year_built',
            field=models.IntegerField(),
        ),
    ]
