# Generated by Django 4.0.4 on 2022-05-11 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_properties__property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='unit',
        ),
        migrations.AddField(
            model_name='links',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
