# Generated by Django 4.0.4 on 2022-05-23 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_unitservices_properties_main_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='main_tenant',
        ),
        migrations.AlterField(
            model_name='tenants',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.units'),
        ),
    ]
