# Generated by Django 3.2.12 on 2022-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_units_servicesss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.CharField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=120)),
                ('address', models.CharField(default='', max_length=120)),
                ('role', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
