# Generated by Django 4.0.4 on 2022-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_properties_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='rented',
            field=models.BooleanField(default=False),
        ),
    ]
