# Generated by Django 3.2.12 on 2022-05-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_properties_main_tenant_alter_tenants_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenan_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='units',
            name='lease_type',
        ),
        migrations.AlterField(
            model_name='tenants',
            name='tenant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenanttype'),
        ),
    ]
