# Generated by Django 4.0.4 on 2022-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='role',
        ),
        migrations.AlterField(
            model_name='tenants',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='email2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='emergency_contact',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='emergency_contact_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='preferred_communications',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='units',
            name='air_conditioning',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='date_deposit_received',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='details',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='extra_resident',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='extra_resident_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='units',
            name='has_pet',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='heating_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='main_tenant_name',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='number_of_pets',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='number_of_residents',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='parking_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='parking_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='payments_email',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='pet_fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='pet_policy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='units',
            name='pets_living',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='rooms',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='square_feet_area',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_number',
            field=models.IntegerField(default=1),
        ),
    ]
