# Generated by Django 4.0.4 on 2022-05-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_links_unit_links_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='units',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
