# Generated by Django 4.0.4 on 2022-05-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_units_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='landlord',
            new_name='property_manager',
        ),
    ]
