# Generated by Django 4.0.4 on 2022-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_rename_landlord_units_property_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='emergency_contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='phone2',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='secondary_communications',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
