# Generated by Django 3.2.12 on 2022-05-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20220524_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='units',
            name='lease_typee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.unitcontracttype'),
        ),
    ]
