# Generated by Django 4.0.4 on 2022-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_remove_tenants_role_alter_tenants_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.URLField(default='', max_length=120),
        ),
    ]
