# Generated by Django 3.2.12 on 2022-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_team_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenants',
            name='email2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='emergency_contact',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='lease_expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='lease_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='phone2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenants',
            name='secondary_communications',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
