# Generated by Django 4.0.4 on 2022-06-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_tenants_email2_alter_tenants_emergency_contact_and_more'),
        ('properties', '0008_auto_20220531_1842'),
    ]

    operations = [
    ]
