# Generated by Django 3.2.12 on 2022-05-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20220524_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='unit',
        ),
    ]
