# Generated by Django 4.0.4 on 2022-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_merge_20220601_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='lease_expiration_date',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='lease_start_date',
        ),
        migrations.AddField(
            model_name='units',
            name='lease_expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='lease_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
