# Generated by Django 3.2.12 on 2022-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_team_landlord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(default='', max_length=120),
        ),
    ]
