# Generated by Django 4.0.4 on 2022-06-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_tenants_lease_expiration_date_and_more'),
        ('properties', '0011_alter_team_email'),
    ]

    operations = [
    ]
