# Generated by Django 4.0.4 on 2022-06-13 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_customuser_organization'),
        ('properties', '0012_merge_20220602_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='landlord',
        ),
        migrations.AddField(
            model_name='properties',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.organizationclient'),
        ),
    ]
