# Generated by Django 4.0.4 on 2022-06-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_customuser_organization'),
        ('properties', '0013_remove_properties_landlord_properties_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='property_manager',
        ),
        migrations.AddField(
            model_name='units',
            name='availability',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='balcony',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='basement_unit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='can_utilities_be_included',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.organizationclient'),
        ),
        migrations.AddField(
            model_name='units',
            name='kids',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='lease_information',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='outdoor_storage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='people_above',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='private_unit',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='unemployed_people',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='utilities_cost',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='utilities_included',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='video_tours',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='units',
            name='yard',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
