# Generated by Django 4.0.4 on 2022-06-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_remove_units_property_manager_units_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='video_tours',
            new_name='video_tour',
        ),
    ]
