# Generated by Django 4.0.4 on 2022-06-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_rename_video_tours_units_video_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='availability',
        ),
    ]
