# Generated by Django 4.0.4 on 2022-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_remove_units_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='availability',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
