# Generated by Django 4.0.4 on 2022-06-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_units_max_weeks_to_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
