# Generated by Django 4.0.4 on 2022-06-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_clientlog'),
        ('payments', '0011_rename_amount_to_pay_unitmonthlypayments_debt_and_more'),
        ('tickets', '0006_suppliers_landlord'),
        ('candidates', '0002_initial'),
        ('book_keeping', '0009_banksaccounts_landlord'),
        ('properties', '0019_alter_units_debt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Property',
        ),
        migrations.RenameModel(
            old_name='PropertyTypes',
            new_name='PropertyType',
        ),
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
        migrations.RenameModel(
            old_name='UnitTypes',
            new_name='UnitType',
        ),
    ]
