# Generated by Django 4.0.4 on 2022-06-15 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0011_delete_clientlog'),
        ('properties', '0020_rename_properties_property_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='landlord',
        ),
        migrations.AddField(
            model_name='property',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='property_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='property',
            name='last_edition_made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='last_time_edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tenants',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.organizationclient'),
        ),
        migrations.AddField(
            model_name='tenants',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenants',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tenants',
            name='last_edition_made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenants',
            name='last_time_edited',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unit_create_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_edition_made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_last_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='last_time_edited',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
