# Generated by Django 4.0.4 on 2022-06-16 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_remove_tenants_landlord_property_create_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='create_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='client',
        ),
    ]
