# Generated by Django 4.0.4 on 2022-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_rename_create_by_unit_created_by_remove_unit_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenants',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
