# Generated by Django 4.0.4 on 2022-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_tenants_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='accessibility_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='ad_title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_bus_stop_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_hospital_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_mall_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_school_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_store_near',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='smoking_permitted',
            field=models.BooleanField(default=False),
        ),
    ]
