# Generated by Django 4.0.4 on 2022-07-04 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0024_unit_accessibility_features_unit_ad_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='tenants',
            name='create_by',
        ),
        migrations.AddField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='property_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenants',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unit_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
