# Generated by Django 4.0.4 on 2022-07-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_remove_unit_pet_fee_remove_unit_pet_friendly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='date_deposit_received',
        ),
    ]
