# Generated by Django 4.0.4 on 2022-07-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_remove_tenants_date_deposit_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
