# Generated by Django 4.0.4 on 2022-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_plan_expired_on_and_more'),
        ('register', '0002_auto_20220520_1053'),
    ]

    operations = [
    ]
