# Generated by Django 4.0.4 on 2022-06-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_has_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='KumbioPlanPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.CharField(max_length=120)),
                ('number_of_clients_allowed', models.IntegerField()),
                ('number_of_units_allowed', models.IntegerField()),
                ('number_of_properties_allowed', models.IntegerField()),
                ('number_of_users_allowed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('name', models.CharField(max_length=120)),
                ('payment_status', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='UserCities',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='plan',
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_delete_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_edit_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='clients_access',
            field=models.CharField(default='1', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='modules_access',
            field=models.CharField(default='1,2,3', max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='property_access',
            field=models.JSONField(default=dict),
        ),
        migrations.RenameModel(
            old_name='UserCountries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='UserPlans',
            new_name='KumbioPlan',
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.kumbioplan'),
        ),
    ]
