# Generated by Django 4.0.4 on 2022-05-11 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_customuser_registration_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersPlans',
            new_name='UserPlans',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan_expired_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 9, 33, 18, 56167)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 9, 33, 18, 56167)),
        ),
    ]
