# Generated by Django 4.0.4 on 2022-06-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_customuser_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clients_access',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='property_access',
        ),
    ]
