# Generated by Django 4.0.4 on 2022-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_customuser_clients_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clients_access',
            field=models.JSONField(default=dict),
        ),
    ]
