# Generated by Django 4.0.4 on 2022-06-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_customuser_clients_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('2', 'CREATE'), ('3', 'EDIT'), ('4', 'DELETE')], max_length=120)),
                ('date_made', models.DateTimeField()),
                ('previous_datA', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.country')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
