# Generated by Django 4.0.4 on 2022-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_clientlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlog',
            name='action',
            field=models.CharField(choices=[('ADD', 'Add'), ('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=120),
        ),
    ]
