# Generated by Django 4.0.4 on 2022-06-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_clientlog_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientLog',
        ),
    ]
