# Generated by Django 4.0.4 on 2022-06-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_delete_clientlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='clients_access',
        ),
    ]
