# Generated by Django 4.0.4 on 2022-06-16 12:32

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_customuser_clients_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
    ]
