# Generated by Django 4.0.4 on 2022-05-23 16:08

from django.db import migrations, models
import django.utils.timezone
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_alter_customuser_plan_expired_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan_expired_on',
            field=models.DateTimeField(default=register.models.seven_day_hence),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
