# Generated by Django 4.0.4 on 2022-06-22 12:26

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0023_alter_customuser_clients_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='password_test',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
    ]
