# Generated by Django 4.0.4 on 2022-06-22 14:35

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_remove_organization_password_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='key',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
