# Generated by Django 4.0.4 on 2022-06-29 13:24

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_customuser_link_to_recover_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_to_recover_password',
            field=models.CharField(default=None, max_length=35, null=True),
        ),
    ]
