# Generated by Django 4.0.4 on 2022-07-01 14:24

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0049_rename_plan_status_customuser_email_is_actived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email_is_actived',
            field=models.BooleanField(default=False),
        ),
    ]
