# Generated by Django 4.0.4 on 2022-07-01 14:44

from django.db import migrations
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0050_alter_customuser_clients_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='link_to_active_email',
            new_name='link_to_activate_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='clients_access',
            field=register.models.IntKeyJSONField(default=dict, validators=[register.models.outer_json_is_object, register.models.outer_json_is_object]),
        ),
    ]
