# Generated by Django 3.2.12 on 2022-05-27 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToWatson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(default='cf7e372a-942c-4070-bf86-1b486a14f8b6', max_length=120, primary_key=True, serialize=False)),
                ('product', models.CharField(default=None, max_length=120, null=True)),
                ('characteristics', models.CharField(default=None, max_length=120, null=True)),
                ('price', models.CharField(default=None, max_length=120, null=True)),
                ('status', models.CharField(default=None, max_length=120, null=True)),
                ('ice_cream', models.CharField(default=None, max_length=120, null=True)),
                ('extra_toppingsss', models.CharField(default=None, max_length=120, null=True)),
                ('drink', models.CharField(default=None, max_length=120, null=True)),
                ('dough', models.CharField(default=None, max_length=120, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('order_code', models.IntegerField(default=0)),
                ('date_time_order', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
