# Generated by Django 4.0.4 on 2022-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='fa860840-335c-411f-8042-946a35217770', max_length=120, primary_key=True, serialize=False),
        ),
    ]
