# Generated by Django 3.2.12 on 2022-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='a0642abb-fe16-462a-a316-1a49d651e77a', max_length=120, primary_key=True, serialize=False),
        ),
    ]
