# Generated by Django 3.2.12 on 2022-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='<function uuid4 at 0x7f7376839670>', max_length=120, primary_key=True, serialize=False),
        ),
    ]
