# Generated by Django 4.0.4 on 2022-05-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='72879f0d-03f3-4f9e-8713-9140b9316f5f', max_length=120, primary_key=True, serialize=False),
        ),
    ]
