# Generated by Django 3.2.12 on 2022-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0002_auto_20220525_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_toppings',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='89fba51d-ca8e-4dde-86b9-17fa48511c19', max_length=120, primary_key=True, serialize=False),
        ),
    ]
