<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-05-26 16:33
=======
# Generated by Django 3.2.12 on 2022-05-26 15:42
>>>>>>> e0b353013b607ec40791a098bdfc95a60b9cfcde

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
<<<<<<< HEAD
            field=models.CharField(default='72879f0d-03f3-4f9e-8713-9140b9316f5f', max_length=120, primary_key=True, serialize=False),
=======
            field=models.CharField(default='<function uuid4 at 0x7fa267dce670>', max_length=120, primary_key=True, serialize=False),
>>>>>>> e0b353013b607ec40791a098bdfc95a60b9cfcde
        ),
    ]
