# Generated by Django 4.0.4 on 2022-05-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='60f55f11-16c3-4cfd-9170-a8c20d47e857', max_length=120, primary_key=True, serialize=False),
        ),
    ]
