# Generated by Django 3.2.12 on 2022-05-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_toppingss',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='<function uuid4 at 0x7fe3c1a1f670>', max_length=120, primary_key=True, serialize=False),
        ),
    ]
