# Generated by Django 3.2.12 on 2022-05-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0003_auto_20220525_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='<function uuid4 at 0x7f2c47ceb700>', max_length=120, primary_key=True, serialize=False),
        ),
    ]
