# Generated by Django 3.2.12 on 2022-05-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0004_auto_20220526_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='<function uuid4 at 0x7f73c96d9670>', max_length=120, primary_key=True, serialize=False),
        ),
    ]
