# Generated by Django 3.2.12 on 2022-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0005_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='email2',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='9bcfbbc0-2bab-41db-a63d-d463932dab06', max_length=120, primary_key=True, serialize=False),
        ),
    ]
