# Generated by Django 4.0.4 on 2022-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0005_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='fa6eccf8-ff5b-4411-ae03-dd2c81334b33', max_length=120, primary_key=True, serialize=False),
        ),
    ]
