# Generated by Django 3.2.12 on 2022-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0006_auto_20220526_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='80db333f-91ef-451c-97fd-cfcb4aea422d', max_length=120, primary_key=True, serialize=False),
        ),
    ]
