# Generated by Django 3.2.12 on 2022-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='3450dbe5-a76b-4009-9c8d-258abb534d26', max_length=120, primary_key=True, serialize=False),
        ),
    ]
