# Generated by Django 3.2.12 on 2022-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0007_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='a098c407-281d-4fc6-90ac-d0a683011727', max_length=120, primary_key=True, serialize=False),
        ),
    ]
