# Generated by Django 3.2.12 on 2022-05-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0008_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='58ba5283-c0c6-47f9-8838-15a4c4b7920c', max_length=120, primary_key=True, serialize=False),
        ),
    ]
