# Generated by Django 3.2.12 on 2022-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='7120cb78-be37-405e-98bf-3d102bab6f26', max_length=120, primary_key=True, serialize=False),
        ),
    ]
