# Generated by Django 3.2.12 on 2022-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0009_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='d634c945-3a63-4e2b-82f8-2d7a84e9b072', max_length=120, primary_key=True, serialize=False),
        ),
    ]
