# Generated by Django 3.2.12 on 2022-05-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0010_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='fca5d675-5cf5-4a52-ae78-aa05ff1d66a8', max_length=120, primary_key=True, serialize=False),
        ),
    ]
