# Generated by Django 3.2.12 on 2022-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0010_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='8e5395eb-6ab0-4daa-ba57-b8bc6b68748c', max_length=120, primary_key=True, serialize=False),
        ),
    ]
