# Generated by Django 3.2.12 on 2022-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0012_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='ed612613-c330-4d7f-9692-f0453fdb71fa', max_length=120, primary_key=True, serialize=False),
        ),
    ]
