# Generated by Django 3.2.12 on 2022-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0013_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='ab5cff24-e919-4a75-a10a-a69476d65155', max_length=120, primary_key=True, serialize=False),
        ),
    ]
