# Generated by Django 3.2.12 on 2022-05-30 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0014_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default=None, max_length=120, null=True)),
                ('details', models.JSONField()),
                ('status', models.CharField(default=None, max_length=120, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('order_code', models.IntegerField(default=0)),
                ('date_time_order', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
