# Generated by Django 3.2.12 on 2022-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0015_auto_20220530_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
