# Generated by Django 4.0.4 on 2022-06-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watson', '0020_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.CharField(max_length=120)),
                ('email_of_attendee', models.EmailField(default=None, max_length=254, null=True)),
                ('duration', models.CharField(max_length=120)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watson.calendar')),
            ],
        ),
    ]
