# Generated by Django 3.2.12 on 2022-05-24 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0018_ticketsteps_name_second_action_link_and_more'),
        ('properties', '0009_remove_units_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanksAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('bank', models.CharField(max_length=100)),
                ('building_if_is_mortgage', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('credit_amount_initial', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('interest_rate', models.CharField(max_length=50)),
                ('interest_payment', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('last_4_digits_of_account', models.CharField(max_length=4)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('date_payment', models.DateField(null=True)),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('month_paid', models.CharField(default='', max_length=20)),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('pending_payment_date', models.DateField(null=True)),
                ('status', models.IntegerField()),
                ('sub_account', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenants')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('kilometers_traveled', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='', max_length=100)),
                ('rate_per_kilometer', models.CharField(max_length=100)),
                ('receipt_number', models.IntegerField(default=0)),
                ('sub_account', models.TextField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_keeping.categories')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units')),
            ],
        ),
    ]
