# Generated by Django 4.0.4 on 2022-05-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('properties', '0002_initial'),
        ('book_keeping', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='book_keeping.categories'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='properties.units'),
        ),
    ]
