# Generated by Django 3.2.12 on 2022-05-26 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        ('properties', '0004_units_servicesss'),
        ('book_keeping', '0004_alter_expenses_categories_alter_expenses_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='supplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.units'),
        ),
    ]
