# Generated by Django 4.0.4 on 2022-05-27 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_units_unit_number'),
        ('tickets', '0001_initial'),
        ('book_keeping', '0004_alter_expenses_categories_alter_expenses_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='categories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_keeping.categories'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='supplier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.units'),
        ),
    ]
