# Generated by Django 4.0.4 on 2022-05-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0005_remove_expenses_category_alter_expenses_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='kilometers_traveled',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='rate_per_kilometer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='sub_account',
            field=models.TextField(default=None, null=True),
        ),
    ]
