# Generated by Django 4.0.4 on 2022-05-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0005_auto_20220526_1814'),
        ('book_keeping', '0006_alter_expenses_description_and_more'),
    ]

    operations = [
    ]
