# Generated by Django 4.0.4 on 2022-05-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_keeping', '0007_merge_20220527_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banksaccounts',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='banksaccounts',
            name='building_if_is_mortgage',
        ),
        migrations.RemoveField(
            model_name='banksaccounts',
            name='monthly_payment',
        ),
    ]
