# Generated by Django 4.0.4 on 2022-06-02 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_keeping', '0008_remove_banksaccounts_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banksaccounts',
            name='landlord',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
