# Generated by Django 4.0.4 on 2022-06-15 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0006_suppliers_landlord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0021_remove_tenants_landlord_property_create_by_and_more'),
        ('register', '0011_delete_clientlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_unit', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_property', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_tenant', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_supplier', models.IntegerField(blank=True, default=None, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=120)),
                ('date_made', models.DateTimeField()),
                ('previous_data', models.JSONField(default=dict)),
                ('new_data', models.JSONField(default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.organizationclient')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers')),
                ('tenant', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.tenants')),
                ('unit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.unit')),
            ],
        ),
    ]
