# Generated by Django 4.0.4 on 2022-05-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintanenceIssueDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('info', models.CharField(default='', max_length=1000, null=True)),
                ('action_link', models.URLField(default='', max_length=120, null=True)),
                ('ticket_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_to_do', models.JSONField()),
                ('issue_description', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuedescription')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('actual_price', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True)),
                ('action_log', models.TextField(null=True)),
                ('followed_up', models.BooleanField(default=False)),
                ('followed_up_commnets', models.CharField(max_length=250, null=True)),
                ('contractor_availability', models.DateField(null=True)),
                ('comments_for_approval', models.TextField(null=True)),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='tickets')),
                ('proposed_contractor', models.IntegerField(null=True)),
                ('contractor_solution', models.CharField(max_length=200, null=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True)),
                ('stimated_time_for_solution', models.IntegerField(null=True)),
                ('specialty', models.CharField(max_length=50, null=True)),
                ('reparation_day', models.DateField(null=True)),
                ('target_completion_date', models.DateField(null=True)),
                ('action_to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenants')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpriority')),
                ('ticket_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketstatus')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units')),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceSubIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('maintanence_issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuetype')),
            ],
        ),
        migrations.AddField(
            model_name='maintanenceissuetype',
            name='maintanence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencetype'),
        ),
        migrations.AddField(
            model_name='maintanenceissuedescription',
            name='maintanence_issue_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencesubissuetype'),
        ),
    ]
