# Generated by Django 4.0.4 on 2022-05-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintanenceIssueDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('last_time_hired', models.DateField(default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('times_hired', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertycities')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_area', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('followed_up', models.BooleanField(default=False)),
                ('contractors_contacted', models.JSONField(default=dict)),
                ('comments_for_approval', models.TextField(null=True)),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField(null=True)),
                ('last_date_ticket_change', models.DateTimeField(default=None, null=True)),
                ('max_for_approval', models.IntegerField(default=250)),
                ('photo', models.ImageField(null=True, upload_to='tickets')),
                ('contractor_solution', models.TextField(null=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True)),
                ('stimated_time_for_solution', models.IntegerField(null=True)),
                ('solution_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('reference_code', models.CharField(max_length=120)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('info', models.CharField(default='', max_length=1000, null=True)),
                ('action_link', models.URLField(default=None, max_length=120, null=True)),
                ('second_action_link', models.URLField(default=None, max_length=120, null=True)),
                ('name_second_action_link', models.CharField(default=None, max_length=120, null=True)),
                ('ticket_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('supplier_attendance', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_to_do', models.JSONField()),
                ('issue_description', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuedescription')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='action_to_do',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketaction'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.suppliers'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenants'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpayment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpriority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuedescription'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketsteps'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.units'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='work_area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkarea'),
        ),
        migrations.CreateModel(
            name='MaintanenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceSubIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_part', models.CharField(max_length=120)),
                ('maintanence_issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuetype')),
            ],
        ),
        migrations.AddField(
            model_name='maintanenceissuetype',
            name='maintanence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencetype'),
        ),
        migrations.AddField(
            model_name='maintanenceissuedescription',
            name='maintanence_issue_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencesubissuetype'),
        ),
        migrations.AddField(
            model_name='maintanenceissuedescription',
            name='work_area',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkarea'),
        ),
    ]
