# Generated by Django 4.0.4 on 2022-05-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintanenceIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuetype')),
            ],
        ),
        migrations.CreateModel(
            name='MaintanenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintanence_type', models.CharField(max_length=120)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype')),
            ],
        ),
        migrations.AddField(
            model_name='maintanenceissuetype',
            name='maintanence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencetype'),
        ),
    ]
