# Generated by Django 4.0.4 on 2022-05-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierWorkAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_are', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='role',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='work_are',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkare'),
        ),
    ]
