# Generated by Django 4.0.4 on 2022-05-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
        ('tickets', '0002_alter_ticket_action_to_do'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertycities')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierrole')),
            ],
        ),
    ]
