# Generated by Django 4.0.4 on 2022-05-30 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_suppliers_rating_alter_suppliers_times_hired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuetype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sub_issue_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanencesubissuetype'),
        ),
    ]
