# Generated by Django 4.0.4 on 2022-05-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_maintanenceissuetype_ticketaction_maintanencetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintanenceIssueDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.CharField(max_length=120)),
                ('maintanence_issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuetype')),
            ],
        ),
    ]
