# Generated by Django 4.0.4 on 2022-05-30 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_issue_type_ticket_sub_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintanenceissuetype',
            name='work_area',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkarea'),
        ),
        migrations.AddField(
            model_name='maintanencesubissuetype',
            name='work_area',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkarea'),
        ),
    ]
