# Generated by Django 4.0.4 on 2022-05-20 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_supplierworkare_remove_suppliers_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='work_area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkare'),
        ),
    ]
