# Generated by Django 4.0.4 on 2022-05-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_supplierrole_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.tickettype'),
        ),
        migrations.DeleteModel(
            name='SupplierRole',
        ),
    ]
