# Generated by Django 4.0.4 on 2022-05-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_maintanencesubissuetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintanencesubissuetype',
            old_name='issue_description',
            new_name='sub_issue_description',
        ),
    ]
