# Generated by Django 4.0.4 on 2022-05-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_work_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='work_area',
        ),
    ]
