# Generated by Django 4.0.4 on 2022-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_suppliers_role_delete_supplierrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contractors_contacted',
            field=models.JSONField(default=dict),
        ),
    ]
