# Generated by Django 4.0.4 on 2022-05-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_work_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierWorkAre',
            new_name='SupplierWorkArea',
        ),
        migrations.AddField(
            model_name='maintanenceissuedescription',
            name='work_area',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tickets.supplierworkarea'),
        ),
    ]
