# Generated by Django 4.0.4 on 2022-05-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_issue_description_maintanencesubissuetype_sub_issue_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketaction',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='ticketaction',
            name='issue_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.maintanenceissuedescription'),
        ),
    ]
