# Generated by Django 4.0.4 on 2022-05-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_contractors_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='last_time_hired',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='times_hired',
            field=models.IntegerField(default=0),
        ),
    ]
