# Generated by Django 4.0.4 on 2022-06-01 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_ticket_stimated_time_for_solution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='landlord',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
