# Generated by Django 4.0.4 on 2022-05-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticketaction_issue_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintanenceissuedescription',
            old_name='issue_description',
            new_name='_string',
        ),
        migrations.RenameField(
            model_name='maintanenceissuetype',
            old_name='issue_type',
            new_name='_string',
        ),
        migrations.RenameField(
            model_name='maintanencesubissuetype',
            old_name='sub_issue_description',
            new_name='_string',
        ),
        migrations.RenameField(
            model_name='maintanencetype',
            old_name='maintanence_type',
            new_name='_string',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='ticket_type',
            new_name='_string',
        ),
    ]
