# Generated by Django 4.0.4 on 2022-07-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0052_alter_customuser_clients_access'),
        ('tickets', '0006_suppliers_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.organization'),
        ),
    ]
