# Generated by Django 4.0.4 on 2022-05-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_rename_supplierworkare_supplierworkarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='work_are',
            new_name='work_area',
        ),
    ]
