# Generated by Django 4.0.4 on 2022-05-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketStatus',
            new_name='TicketSteps',
        ),
    ]
