# Generated by Django 4.0.4 on 2022-05-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_issue_description_maintanenceissuedescription__string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintanenceissuedescription',
            old_name='maintanence_issue_type',
            new_name='maintanence_issue_sub_type',
        ),
        migrations.RenameField(
            model_name='maintanencesubissuetype',
            old_name='maintanence_issue_sub_type',
            new_name='maintanence_issue_type',
        ),
    ]
