# Generated by Django 4.0.4 on 2022-05-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_ticketstatus_ticketsteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.JSONField(default=dict),
        ),
    ]
