# Generated by Django 4.0.4 on 2022-05-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_maintanence_issue_type_maintanenceissuedescription_maintanence_issue_sub_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketaction',
            old_name='action',
            new_name='_string',
        ),
    ]
