# Generated by Django 4.0.4 on 2022-07-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='owner',
            new_name='opened_by',
        ),
    ]
