# Generated by Django 4.0.4 on 2022-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_work_are_supplierworkarea_work_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierworkarea',
            name='work_are',
            field=models.CharField(default='120', max_length=120),
        ),
    ]
