# Generated by Django 4.0.4 on 2022-05-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_rename_action_ticketaction__string'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments_for_approval',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contractor_availability',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(null=True, upload_to='tickets'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quoted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reparation_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stimated_time_for_solution',
            field=models.IntegerField(null=True),
        ),
    ]
