# Generated by Django 4.0.4 on 2022-05-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_ticket_comments_ticketcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomments',
            old_name='created_by',
            new_name='ticket',
        ),
    ]
