# Generated by Django 4.0.4 on 2022-05-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketpriority_alter_ticket_actual_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketpriority',
            old_name='string',
            new_name='_string',
        ),
    ]
