# Generated by Django 4.0.4 on 2022-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_rename_string_ticketpriority__string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comments_for_approval',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contractor_availability',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contractor_solution',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='followed_up_commnets',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
