# Generated by Django 4.0.4 on 2022-05-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_comments_for_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_close',
            new_name='date_closed',
        ),
    ]
