# Generated by Django 4.0.4 on 2022-05-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_rename_date_close_ticket_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority_d',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpriority'),
        ),
    ]
