# Generated by Django 4.0.4 on 2022-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticketsteps_action_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='reparation_day',
            new_name='solution_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='proposed_contractor',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='specialty',
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_date_ticket_change',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contractor_solution',
            field=models.TextField(null=True),
        ),
    ]
