# Generated by Django 4.0.4 on 2022-05-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_priority_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='priority_d',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpriority'),
        ),
    ]
