# Generated by Django 4.0.4 on 2022-05-23 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_rename_reparation_day_ticket_solution_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('reference_code', models.CharField(max_length=120)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='action_to_do',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketaction'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketpayment'),
        ),
    ]
