# Generated by Django 4.0.4 on 2022-05-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_remove_ticket_priority_d_alter_ticket_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintanenceissuedescription',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='maintanenceissuetype',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='maintanencesubissuetype',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='maintanencetype',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='ticketaction',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='ticketpriority',
            old_name='_string',
            new_name='string_part',
        ),
        migrations.RenameField(
            model_name='tickettype',
            old_name='_string',
            new_name='string_part',
        ),
    ]
