# Generated by Django 4.0.4 on 2022-05-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticketpayment_alter_ticket_action_to_do_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='action_log',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='contractor_availability',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='followed_up_commnets',
        ),
    ]
