# Generated by Django 4.0.4 on 2022-05-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_remove_ticket_action_log_remove_ticket_actual_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='target_completion_date',
        ),
    ]
